name: ekramproject
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_vector_icons: ^2.0.0
  provider: ^6.0.0
  http: ^1.2.1
  url_launcher: ^6.2.6
  pdf: ^3.6.5
  printing: ^5.5.0
  path_provider: ^2.0.5
  dash_chat_2: ^0.0.18
  google_maps_flutter: ^2.2.8
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  google_generative_ai: ^0.4.2
  flutter_staggered_animations: ^1.1.1
  dropdown_search: ^5.0.6
  # flutter_typeahead: ^5.2.0
  # file_picker: ^8.0.3
  # geolocator: ^12.0.0
  # permission_handler: ^11.3.1
  # rive: 0.13.5
  # flutter_hooks: ^0.18.0
  # animated_drawer: ^0.1.4
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/
    - pictures/
  
